Traceback (most recent call last):
  File "D:\project\Python\AICup2021\Src\Agent.py", line 25, in <module>
    player.update(lastActionTakenByThePlayer, x, y, health, healthUpgradeCount, bombRange, trapCount)
  File "D:\project\Python\AICup2021\Src\Player.py", line 30, in update
    self.lastAction = Action(lastAction)
  File "C:\Users\Amirhosein\AppData\Local\Programs\Python\Python39\lib\enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Amirhosein\AppData\Local\Programs\Python\Python39\lib\enum.py", line 702, in __new__
    raise ve_exc
ValueError: 10 is not a valid Action
